# fly.toml app configuration file generated for miniature-gnatt-chart-688f on 2024-09-13T22:24:55-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'miniature-gnatt-chart-688f'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '5s'
swap_size_mb = 512

[experimental]
  cmd = ['start.sh']
  entrypoint = ['sh']
  auto_rollback = true
  [experimental.attached]
    secrets = { }
[metrics]
port = 9091
path = "/metrics"
[env]
  BUN_PORT="3000"
  FORCE_COLOR="1"
[build]
# image = "flyio/redis:6.2.6"
[[mounts]]
  source = 'data'
  destination = '/data'
  # source = "litefs"
  # destination = "/var/lib/litefs"
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

  [[services.http_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'get'
    path = '/healthcheck'
    protocol = 'http'
    tls_skip_verify = false

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
